---
- hosts: overcloud
  vars:
    metadata:
      name: Hardware Discovery
      description: Validations that run after the hardware was discovered.
      stage: discovery
- include: ../validations/discovery_diff.yaml
- include: ../validations/undercloud-disk-space.yaml
- include: ../validations/512e.yaml
