#!/bin/bash

# NOTE: place this at: /usr/local/bin/run-validation

set -ex

echo Sourcing stackrc
source /home/stack/stackrc

# Make sure ssh is not asking interactively for hosts it can't check the key
# authenticity
export ANSIBLE_HOST_KEY_CHECKING=False

echo Running validation
# TODO(mandre) run the validation passed as argument
ansible-playbook -i /usr/share/tripleo-validations/tripleo-ansible-inventory.py \
  /usr/share/tripleo-validations/validations/haproxy.yaml

echo Validation finished
