---
- hosts: undercloud
  become: true
  vars:
    metadata:
      name: Rogue DHCP
      description: Locate rogue DHCP servers on Pacemaker-managed networks
      groups:
        - prep
        - pre-introspection
        - pre-deployment
  tasks:
  - name: Install scapy
    pip: name=scapy state=present virtualenv=/tmp/validations-venv
  - name: Look for rogue DHCP servers
    script: files/rogue_dhcp.py
